#name : eSIM Admin Console 빌드 및 배포
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Github esim_express Repository 파일 불러오기
#        uses: actions/checkout@v4
#
#      - name: JDK 21버전 설치
#        uses: actions/setup-java@v4
#        with:
#          distribution: temurin
#          java-version: 21
#          cache: gradle
#
#      - name: application-prod.yml 파일 만들기
#        run: echo "${{ secrets.APPLICATION_PROPERTIES_PROD }}" > ./src/main/resources/application-prod.yml
#
#      - name: application-dev.yml 파일 만들기
#        run: echo "${{ secrets.APPLICATION_PROPERTIES_DEV }}" > ./src/main/resources/application-dev.yml
#
#      - name: 테스트 및 빌드하기
#        run: ./gradlew clean build
#
#      - name: 빌드된 파일 이름 변경하기
#        run: mv ./build/libs/esim_admin_console.jar ./esim_admin_console.jar
#
#      - name: Upload jar to server
#        uses: appleboy/scp-action@v0.1.7
#        with:
#          host: ${{ secrets.SERVER_HOST }}
#          port: ${{ secrets.SERVER_PORT }}
#          username: ${{ secrets.SERVER_USERNAME }}
#          password: ${{ secrets.SERVER_PASSWORD }}
#          source: "esim_admin_console.jar"
#          target: "/home/${{ secrets.SERVER_USERNAME }}/app"
#          overwrite: true
#
#
#      - name: Restart server
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.SERVER_HOST }}
#          port: ${{ secrets.SERVER_PORT }}
#          username: ${{ secrets.SERVER_USERNAME }}
#          password: ${{ secrets.SERVER_PASSWORD }}
#          script_stop: true     # 이전 세션 종료
#          script: |
#            cd /home/${{ secrets.SERVER_USERNAME }}/app/
#            echo ${{ secrets.SERVER_PASSWORD }} | sudo -S fuser -k -n tcp 8082 || true
#            echo ${{ secrets.SERVER_PASSWORD }} | sudo -S fuser -k -n tcp 8083 || true
#            bash -lc "nohup java -jar esim_admin_console.jar >> web.log 2>&1 &"